[project]
name = "pychess"
version = "0.1.0"
description = "cli chess game created in python for boot.dev hackathon 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "rich>=14.1.0",
]
